<a href="https://colab.research.google.com/github/Sanazzzmi/Sentiment_analysis_of_the_English_text_with_word_embedding_-_frequency_word/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import testing data

In [ ]:
import pandas as pd
import csv
d = 200

df = pd.read_csv("STG.txt",sep=';')
df.columns = ['id','sentiment','tweet']
df["sentiment"].replace({4: 1}, inplace=True)
df

id  sentiment                                              tweet
0     1467933112          0  the angel is going to miss the athlete this we...
1     2323395086          0  It looks as though Shaq is getting traded to C...
2     1467968979          0     @clarianne APRIL 9TH ISN'T COMING SOON ENOUGH 
3     1990283756          0  drinking a McDonalds coffee and not understand...
4     1988884918          0  So dissapointed Taylor Swift doesnt have a Twi...
...          ...        ...                                                ...
2029  1468049681          0  A king sized bed is nice but sad and lonely wi...
2030  2195475499          0  @breannalovesjb hurry up home!!!!! im dying wi...
2031  1996172176          0  @jordanhowell lol only a PSP, had a game boy b...
2032  2016105580          1  Good morning everyone!  It is such a beautiful...
2033  2186977170          1  hey guess was @magicmanil the Lakers won and K...

[2034 rows x 3 columns]

# preprocessing testing data

In [ ]:
contractions = { 
"ain't": "am not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he'll've": "he will have",
"he's": "he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how does",
"i'd": "i would",
"i'd've": "i would have",
"i'll": "i will",
"i'll've": "i will have",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
"it'd": "it would",
"it'd've": "it would have",
"it'll": "it will",
"it'll've": "it will have",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she would",
"she'd've": "she would have",
"she'll": "she will",
"she'll've": "she will have",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so is",
"that'd": "that would",
"that'd've": "that would have",
"that's": "that is",
"there'd": "there would",
"there'd've": "there would have",
"there's": "there is",
"they'd": "they would",
"they'd've": "they would have",
"they'll": "they will",
"they'll've": "they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
" u ": " you ",
" ur ": " your ",
" n ": " and "}

In [ ]:
import re

text = ' '.join(df['tweet'])
text = text.split()
freq_comm = pd.Series(text).value_counts()
rare = freq_comm[freq_comm.values == 1]

def get_clean_text(x):
    if type(x) is str:
        x = x.lower()
        for key in contractions:
            value = contractions[key]
            x = x.replace(key, value)
        x = re.sub(r'([a-zA-Z0-9+._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)', '', x) 
        #regex to remove to emails
        x = re.sub(r'(http|ftp|https)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', x)
        #regex to remove URLs
        x = re.sub('RT', "", x)
        #substitute the 'RT' retweet tags with empty spaces
        x = re.sub('[^A-Z a-z]+', '', x)
        #combining all the text excluding rare words.
        x = ' '.join([t for t in x.split() if t not in rare])
        return x
    else:
        return x
    
df['tweet'] = df['tweet'].apply(lambda x: get_clean_text(x))
df['tweet']

0             the angel is going to miss the this weekend
1       it looks as though shaq is getting to clevelan...
2            clarianne april th is not coming soon enough
3       drinking a mcdonalds coffee and not why someon...
4                   so taylor swift doesnt have a twitter
                              ...                        
2029    a king bed is nice but sad and lonely with no ...
2030    breannalovesjb hurry up home im dying with no ...
2031    jordanhowell lol only a psp had a game boy but...
2032    good morning everyone it is such a beautiful d...
2033    hey guess was magicmanil the lakers won and ko...
Name: tweet, Length: 2034, dtype: object

In [ ]:
df['sentiment'].value_counts()

0    1402
1     632
Name: sentiment, dtype: int64

In [ ]:
text = df['tweet'].tolist()
y = df['sentiment']

# Each word has an id

In [ ]:
from keras.preprocessing.text import Tokenizer
token = Tokenizer()
token.fit_on_texts(text)
#token.word_index.items()

In [ ]:
vocab_size  = len(token.word_index) + 1
vocab_size

3637

# Each sentence is written according to the number of the word

In [ ]:
encoded_text = token.texts_to_sequences(text)
print(encoded_text[:3])

[[3, 851, 6, 37, 2, 77, 3, 26, 248], [9, 274, 97, 180, 716, 6, 203, 2, 717, 2, 183, 89, 46, 132, 10, 1062, 476, 3, 230, 1505, 6, 34, 92], [1506, 1063, 258, 6, 12, 311, 259, 362]]


In [ ]:
from keras.preprocessing.sequence import pad_sequences
max_length = 120
X = pad_sequences(encoded_text, maxlen=max_length, padding='post')
print(X)

[[   3  851    6 ...    0    0    0]
 [   9  274   97 ...    0    0    0]
 [1506 1063  258 ...    0    0    0]
 ...
 [3635   96  159 ...    0    0    0]
 [  40  138  284 ...    0    0    0]
 [ 190  197   22 ...    0    0    0]]


# use word embedding glove

In [ ]:
import numpy as np
glove_vectors = dict()
# file = open('glove.twitter.27B.200d.txt', encoding='utf-8')
file = open('glove.twitter.27B.200d.txt', encoding='utf-8')

for line in file:
    values = line.split()
    word = values[0]
    #storing the word in the variable
    vectors = np.asarray(values[1: ])
    #storing the vector representation of the respective word in the dictionary
    glove_vectors[word] = vectors
file.close()
len(glove_vectors)

1193515

In [ ]:
glove_vectors.get('you')

array(['0.1964', '0.67153', '0.0062976', '0.25359', '-0.42097', '0.3849',
       '1.0378', '-0.18536', '-0.054244', '-0.10856', '0.12146',
       '0.047692', '-0.93228', '-0.27192', '-0.3506', '0.11069',
       '-0.055099', '-0.079658', '0.011767', '0.14395', '-0.025917',
       '-0.18253', '0.025691', '0.19619', '0.10334', '1.0731', '0.41992',
       '0.17083', '0.91596', '-0.43398', '0.16464', '0.012715',
       '0.095477', '0.1449', '-0.29652', '-0.10642', '0.098389',
       '0.17937', '0.23289', '-0.22209', '0.08777', '-0.18005', '0.38678',
       '-0.032059', '0.1202', '-0.41741', '0.26827', '-0.19769',
       '0.021976', '-0.23585', '0.14789', '0.10173', '-0.1038',
       '-0.31954', '0.63308', '-0.051142', '-0.053209', '0.29378',
       '-0.054395', '4.3346e-05', '0.25585', '-0.18048', '-0.2703',
       '0.0077783', '0.63585', '0.14869', '-0.10854', '-0.24726',
       '-0.10869', '-0.24147', '0.28059', '0.13645', '-0.03561',
       '-0.68258', '0.11957', '0.011085', '-0.013771',

In [ ]:
glove_vectors.get('yogdfgfdgdgu')

# Find words in word embedding

In [ ]:
word_vector_matrix = np.zeros((vocab_size, d))


not_word = []
have_word = []

for word, index in token.word_index.items()  :# هر کلمه یه شناسه داره
    vector = glove_vectors.get(word)
    if vector is not None:
        word_vector_matrix[index] = vector
        have_word.append(word)
    else:
        not_word.append(word)
        
        
#have_word =>Words in word embedding

# How many words are seen in positive sentences and how many in negative sentences

In [ ]:
#Divide tweets into tags of one and tags of zeros
df_y = pd.DataFrame(np.array(y),columns=['a'])
df_one = df_y[df_y['a']==1].index.values.astype(int)
df_zero = df_y[df_y['a']==0].index.values.astype(int)

text_one = []
for x in df_one:
    text_one.append(text[x])

text_zero = []
for x in df_zero:
    text_zero.append(text[x])

join_text_zero = [' '.join(text_zero)]
join_text_one = [' '.join(text_one)]

df_join_text_zero = pd.DataFrame(join_text_zero[0:],columns= ["tex"])
df_join_text_one = pd.DataFrame(join_text_one[0:],columns= ["tex"])

df_have_word = pd.DataFrame({'word':have_word})
df_token = pd.DataFrame.from_dict(token.word_index.items())

df_text_one = pd.DataFrame(text_one[0:],columns= ["tex"])
df_text_zero = pd.DataFrame(text_zero[0:],columns= ["tex"])

from collections import Counter
count_zero = df_join_text_zero['tex'].str.split().apply(Counter)
count_one = df_join_text_one['tex'].str.split().apply(Counter)

df_counter_zero = pd.DataFrame.from_dict(count_zero[0], orient='index').reset_index()
df_counter_one = pd.DataFrame.from_dict(count_one[0], orient='index').reset_index()
df_counter_zero.columns = ['word', 'value']
df_counter_one.columns = ['word', 'value']

df_token.columns = ['word', 'id']

sentiment_zero =df_have_word.merge(df_counter_zero, left_on='word', right_on='word')[['value','word']]
sentiment_one = df_have_word.merge(df_counter_one, left_on='word', right_on='word')[['value','word']]

#Words found in both positive and negative sentences
common = sentiment_one.merge(sentiment_zero,on=['word','word'])
common.columns = ['value_one', 'word' , 'value_zero']

common["max"] = common[["value_one", "value_zero"]].max(axis=1)
common["min"] = common[["value_one", "value_zero"]].min(axis=1)

#Words that were both positive and negative in the sentence were marked with a label column that were more commonly seen in positive or negative sentences.
common["lable"] = np.where(common["value_one"] == common["max"], 1, 0)
common["frequent_negative_sentence"] = np.where(common["lable"] == 1 , common["min"], common["max"])
common["frequent_positive_sentence"] = np.where(common["lable"] == 0 , common["min"], common["max"])

common_df_final = common.drop('value_one', 1)
common_df_final = common_df_final.drop('value_zero', 1)
common_df_final = common_df_final.drop('max', 1)
common_df_final = common_df_final.drop('min', 1)

#Those words that are seen in positive sentences and not seen in negative sentences
just_one = sentiment_one[(~sentiment_one.word.isin(common.word))&(~sentiment_one.word.isin(common.word))]
just_one = just_one.assign(lable = 1)
just_one = just_one.assign(frequent_negative_sentence = 0)
just_one.columns = ['frequent_positive_sentence', 'word' , 'lable','frequent_negative_sentence']

#Those words that are seen in negative sentences and not seen in positive sentences
just_zero = sentiment_zero[(~sentiment_zero.word.isin(common.word))&(~sentiment_zero.word.isin(common.word))]
just_zero = just_zero.assign(lable = 0)
just_zero = just_zero.assign(frequent_posoitve_sentence = 0)
just_zero.columns = ['frequent_negative_sentence', 'word' , 'lable','frequent_positive_sentence']

frames = [common_df_final,just_zero, just_one]
result = pd.concat(frames)


result

word  lable  frequent_negative_sentence  \
0               i      0                         980   
1              to      0                         582   
2             the      0                         503   
3               a      0                         364   
4              my      0                         404   
...           ...    ...                         ...   
1403     whithout      1                           0   
1404     notebook      1                           0   
1405  coincidence      1                           0   
1406         gsoc      1                           0   
1407         cafe      1                           0   

      frequent_positive_sentence  
0                            325  
1                            261  
2                            253  
3                            163  
4                            113  
...                          ...  
1403                           1  
1404                           1  
1405                           1  
1406                           1  
1407                           1  

[2557 rows x 4 columns]

# WI calculation

In [ ]:
result['WI_positive_word'] = np.where(result['lable']== 1 , 1- result['frequent_negative_sentence']/ result['frequent_positive_sentence'], None)
result['WI_negative_word'] = np.where(result['lable']== 0 , 1- result['frequent_positive_sentence']/ result['frequent_negative_sentence'], None)
result['WI'] = result['WI_positive_word'].fillna(result['WI_negative_word'])
result

word  lable  frequent_negative_sentence  \
0               i      0                         980   
1              to      0                         582   
2             the      0                         503   
3               a      0                         364   
4              my      0                         404   
...           ...    ...                         ...   
1403     whithout      1                           0   
1404     notebook      1                           0   
1405  coincidence      1                           0   
1406         gsoc      1                           0   
1407         cafe      1                           0   

      frequent_positive_sentence WI_positive_word WI_negative_word        WI  
0                            325             None         0.668367  0.668367  
1                            261             None         0.551546  0.551546  
2                            253             None         0.497018  0.497018  
3                            163             None         0.552198  0.552198  
4                            113             None         0.720297  0.720297  
...                          ...              ...              ...       ...  
1403                           1              1.0             None  1.000000  
1404                           1              1.0             None  1.000000  
1405                           1              1.0             None  1.000000  
1406                           1              1.0             None  1.000000  
1407                           1              1.0             None  1.000000  

[2557 rows x 7 columns]

# Find words in the sentence that are in word embedding

In [ ]:
word_have_list= list(result.word)
word_have_set = set(word_have_list)
result_word_list = result['word'].tolist()
result_WI_list = result['WI'].tolist()

def word_WI_finder(x):
    df_words = set(x.split(' '))
    extract_words =  word_set.intersection(df_words)
    #index_word = result_word_list.index(extract_words)
    
    
    return (extract_words)


word_set = word_have_set

df['ddd_WI'] = df.tweet.apply(word_WI_finder)

# Calculate weight

In [ ]:
WI_ww = []
for x in df['ddd_WI'][:]:
    WI_w = []
    for y in x : 
        ind = result_word_list.index(y)
        WI_w.append(result_WI_list[ind])
    WI_ww.append(WI_w)
    
WI_ww_new = [[] if x==[0] else x for x in WI_ww]
WI_ww_neww = [[] if x==[0,0] else x for x in WI_ww_new]
Weight_sentence = [[float(j)/sum(i) for j in i] for i in WI_ww_neww[:]]
#Weight_sentence

# Calculate the final sentence vector

In [ ]:
sentence_ss = []
for i in range(len(df['ddd_WI'][:])):
    #print(df['ddd_WI'][x])
    vv = []
    for j in range(len(df['ddd_WI'][i])):
        #print(list(df['ddd_WI'][i])[j])
        if len(Weight_sentence[i]) > 1:
            v = []
            for num in range(d):
                vec = Weight_sentence[i][j] * float(glove_vectors.get(list(df['ddd_WI'][i])[j])[num])
                v.append(vec)
            #print(v)
            vv.append(v)
        #print(vv)
        else:
            vv.append(glove_vectors.get(list(df['ddd_WI'][i])[j]).astype(np.float))
            
    s = [sum(x) for x in zip(*vv)]
    sentence_ss.append(s)

sentence_ss[0]

data = pd.DataFrame(sentence_ss[0:] , columns = list(range(d)))
#X_test = data[:]
#y_test = df['sentiment'][:]
data[:].to_csv('X_test.csv', sep='\t', encoding='utf-8')
df['sentiment'][:].to_csv('y_test.csv', sep='\t', encoding='utf-8')

#d = pd.read_csv("s.csv",sep='\t')